import { describe, expect, test } from "bun:test";
import { ReminderEngine, selectReminders, type ReminderPlan, type ReminderEntry, type ScheduledReminder } from "./reminder-engine";
const plan:ReminderPlan={userId:"user-a",timezone:"UTC",entries:[{identifier:"todo-1:2026-09-12",title:"Read",day:"2026-09-12",time:"12:00"}]};
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};}
function harness(){
 const rows=new Map<string,ScheduledReminder>();let owner="token-a";let granted=true;let fail=false;const calls:string[]=[];
 let hook:((n:ReminderEntry)=>Promise<void>)|undefined;
 const engine=new ReminderEngine({available:true,getOwner:()=>owner,now:()=>Date.parse("2026-09-11T00:00:00Z"),permitted:async()=>granted,list:async()=>[...rows.values()],cancel:async id=>{calls.push("cancel:"+id);rows.delete(id);},schedule:async n=>{calls.push("schedule:"+n.identifier);if(hook)await hook(n);if(fail)throw Error("OS unavailable");rows.set(n.identifier,n);}});
 return{engine,rows,calls,setOwner:(x:string)=>owner=x,setGranted:(x:boolean)=>granted=x,setFail:(x:boolean)=>fail=x,setHook:(h:typeof hook)=>hook=h};
}
describe("local reminder reconciliation (mock OS)",()=>{
 test("unchanged refresh is a no-op; edit replaces; completion removes; undo restores",async()=>{const h=harness();expect(await h.engine.sync(plan)).toBe(true);const count=h.calls.length;await h.engine.sync(plan);expect(h.calls.length).toBe(count);await h.engine.sync({...plan,entries:plan.entries.map(n=>({...n,time:"13:00"}))});expect(h.calls.length).toBe(count+2);await h.engine.sync({...plan,entries:[]});expect(h.rows.size).toBe(0);await h.engine.sync(plan);expect(h.rows.size).toBe(1);});
 test("permission denial does not schedule and recovery works",async()=>{const h=harness();h.setGranted(false);expect(await h.engine.sync(plan)).toBe(false);expect(h.rows.size).toBe(0);h.setGranted(true);expect(await h.engine.sync(plan)).toBe(true);});
 test("logout during pending OS schedule cancels late result and preserves unrelated notifications",async()=>{const h=harness();h.rows.set("other-app",{identifier:"other-app"});const started=deferred(),release=deferred();h.setHook(async()=>{started.resolve();await release.promise;});const sync=h.engine.sync(plan);await started.promise;h.setOwner("");const clear=h.engine.clear();release.resolve();expect(await sync).toBe(false);await clear;expect([...h.rows.keys()]).toEqual(["other-app"]);});
 test("newer plan wins over in-flight older plan",async()=>{const h=harness();const started=deferred(),release=deferred();h.setHook(async()=>{started.resolve();await release.promise;});const old=h.engine.sync(plan);await started.promise;const newer=h.engine.sync({...plan,entries:[]});release.resolve();expect(await old).toBe(false);expect(await newer).toBe(true);expect(h.rows.size).toBe(0);});
 test("account switch invalidates queued work without token in notification content",async()=>{const h=harness();const old=h.engine.sync(plan);h.setOwner("token-b");expect(await old).toBe(false);await h.engine.sync({...plan,userId:"user-b"});expect(JSON.stringify([...h.rows.values()])).not.toContain("token-");expect([...h.rows.values()][0].ownerId).toBe("user-b");});
 test("cold start preserves same-user offline schedules but clears foreign and legacy",async()=>{const h=harness();await h.engine.sync(plan);h.rows.set("task-2",{identifier:"task-2"});h.rows.set("todo-3",{identifier:"todo-3",ownerId:"user-b"});await h.engine.clear("user-a");expect([...h.rows.keys()]).toEqual([plan.entries[0].identifier]);});
 test("OS failure returns false and serialized queue remains usable",async()=>{const h=harness();h.setFail(true);expect(await h.engine.sync(plan)).toBe(false);h.setFail(false);expect(await h.engine.sync(plan)).toBe(true);});
 test("inactive/unmounted plan cannot schedule",async()=>{const h=harness();expect(await h.engine.sync(plan,()=>false)).toBe(false);expect(h.rows.size).toBe(0);});
 test("bounded nearest-first queue: 12/item, 60 globally minus unrelated, de-duplicated",()=>{const entries=Array.from({length:10},(_,t)=>Array.from({length:20},(_,d)=>({identifier:`todo-${t}:2026-09-${String(d+11).padStart(2,"0")}`,title:"Task",day:`2026-09-${String(d+11).padStart(2,"0")}`,time:"12:00"}))).flat();const all=selectReminders({...plan,entries:[...entries,...entries]},[],Date.parse("2026-09-11T00:00:00Z"));expect(all).toHaveLength(60);expect(new Set(all.map(n=>n.identifier)).size).toBe(60);expect(all[0].date.getTime()).toBeLessThanOrEqual(all[59].date.getTime());expect(selectReminders({...plan,entries:entries.filter(n=>n.identifier.startsWith("todo-0:"))},[],0)).toHaveLength(12);expect(selectReminders({...plan,entries},Array.from({length:59},(_,i)=>({identifier:`unrelated-${i}`})),0)).toHaveLength(1);});
 test("stale refresh capture invalidates on clear, not normal sync",async()=>{const h=harness();const active=h.engine.capture();await h.engine.sync(plan,active);expect(active()).toBe(true);await h.engine.clear();expect(active()).toBe(false);});
});
