export const welcomeQuote = "Small steps, kept quietly, become the shape of who you are.";

export const themes = [
  { id: "quiet", number: "01", name: "Quiet Paper", subtitle: "The original, softened.", material: "Crumpled ivory paper", light: "An almost-still warm light", mood: "Familiar · grounded · quiet", description: "A little texture. A lot of breathing room. The closest to your reference, with soft creases that disappear into an open, ivory page.", detail: "Light moves so gently you might only notice it when you pause.", colors: ["#f3f0e6", "#24221d", "#ae4e32"] },
  { id: "sunlit", number: "02", name: "Sunlit Paper", subtitle: "Room for a little warmth.", material: "Sun-warmed ivory paper", light: "Slow, diffuse window shadows", mood: "Warm · hopeful · unhurried", description: "Like opening a notebook beside a window. A wash of morning light and a passing shadow bring a small, ordinary moment to life.", detail: "The shadows stay in the background. Your first small step stays in focus.", colors: ["#f2e7d1", "#282219", "#a84b2e"] },
  { id: "ink", number: "03", name: "Ink & Wash", subtitle: "A softer kind of expression.", material: "Handmade paper & earthy wash", light: "Slow-moving pigment layers", mood: "Expressive · organic · personal", description: "Ochre and terracotta settle around the edges, leaving a clear space for the words. A welcome that feels made by hand.", detail: "The color moves on a long, gentle cycle. Nothing competes with the quote.", colors: ["#f4eddf", "#30251e", "#a04d36"] },
  { id: "linen", number: "04", name: "Soft Linen", subtitle: "Simple, down to the fibers.", material: "Fine, warm ivory linen", light: "A broad sweep of soft light", mood: "Tactile · understated · warm", description: "A fine weave takes the place of paper creases. Warm brown ink and a clay-colored button make the simplest direction feel considered.", detail: "A soft light passes over the weave, without moving the fabric itself.", colors: ["#eee7da", "#352b24", "#96513e"] },
  { id: "midnight", number: "05", name: "Midnight Paper", subtitle: "Quiet, after everything else.", material: "Deep charcoal paper", light: "Low, copper-toned illumination", mood: "Intimate · restful · focused", description: "Warm-white words on charcoal paper. A muted copper accent brings just enough warmth to a welcome made for a quieter hour.", detail: "Low ambient light moves across the paper. No glow, stars or distractions.", colors: ["#272621", "#f3eee2", "#aa6247"] },
] as const;

export type WelcomeTheme = (typeof themes)[number];
